name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Current Date
        run: |
          date
      - name: Current Directory
        run: |
          ls -l
      - name: Say hello
        run: |
          echo "Hello World!"
